### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by EmporiumNetwork** [CustomiesDevs/Customies#59]
[Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function customiesdevs\customies\util\Cache::__construct(), 0 passed in phar://C:/Users/brant/Desktop/EmporiumSkyBlock/PocketMine-MP.phar/src/utils/SingletonTrait.php on line 31 and exactly 1 expected" (EXCEPTION) in "plugins/Emporium-Core/src/customiesdevs/customies/util/Cache" at line 32
--- Stack trace ---
  #0 pmsrc/src/utils/SingletonTrait(31): customiesdevs\customies\util\Cache->__construct()
  #1 pmsrc/src/utils/SingletonTrait(36): customiesdevs\customies\util\Cache::make()
  #2 plugins/Emporium-Core/src/customiesdevs/customies/item/CustomiesItemFactory(74): customiesdevs\customies\util\Cache::getInstance()
  #3 plugins/Emporium-Core/src/Emporium/Core/Main(265): customiesdevs\customies\item\CustomiesItemFactory->registerItem(string[20] pocketmine\item\Item, string[14] gem:common_gem, string[10] Common Gem)
  #4 pmsrc/src/plugin/PluginBase(118): Emporium\Core\Main->onEnable()
  #5 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #6 pmsrc/src/Server(1417): pocketmine\plugin\PluginManager->enablePlugin(object Emporium\Core\Main#22169)
  #7 pmsrc/src/Server(1030): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21906)
  #8 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#4, object pocketmine\utils\MainLogger#3, string[40] C:\Users\brant\Desktop\EmporiumSkyBlock\, string[48] C:\Users\brant\Desktop\EmporiumSkyBlock\plugins\)  #9 pmsrc/src/PocketMine(362): pocketmine\server()
  #10 pmsrc(11): require(string[84] phar://C:/Users/brant/Desktop/EmporiumSkyBlock/PocketMine-MP.phar/src/PocketMine)
--- End of exception information ---

**Comment by morcheysha77** [comment]
A simple mistake is not always enough to solve a problem. Please send the part of your core that uses Customies, thank you.

**Comment by EmporiumNetwork** [comment]
register the item onEnable
CustomiesItemFactory::getInstance()->registerItem(Item::class, "gem:common_gem", "Common Gem");

creating the item in a seperate items class 
public function Common(): Item {

        $item = CustomiesItemFactory::getInstance()->get("gem:common_gem");
        $item->setCustomName("§l§fCommon §r§aGem");
        $item->setLore([
            "§r",
            "§l§eRewards List",
            "§r§8 * §71x Common Kit",
            "§r§8 * §71x Common Tag",
            "§r§8 * §71x Common Money Pouch",
            "§r§8 * §71x Common Spawner",
            "§r",
            "§r§8 * §7Tier: §aI",
            "§r",
            "§r§8 * §eRight-click to Decrypt the gem."]);
        $item->addEnchantment(GlowManager::$enchInst);
        $item->getNamedTag()->setByte("CommonGem", 1);

        return $item;

    }

**Comment by morcheysha77** [comment]
- The error comes from the fact that Cache::getInstance() is null because it does not load correctly, and therefore executes the `Cache::make()` function. 
Except `Cache::__construct(string $cacheFile)` needs `$cacheFile` which `Cache::make()` does not take into account. 

- But I see "Emporium-Core/src/customiesdevs/customies/util/Cache", you didn't put the Customies plugin in your Core, if so, you probably forgot also called the onLoad.

**Comment by EmporiumNetwork** [comment]
the plugin is in my core

**Comment by morcheysha77** [comment]
- Customies is a plugin, so it's normal to respect this, it's not a library.
- I therefore invite you to download the latest version on poggit: https://poggit.pmmp.io/p/Customies to put directly in `/plugins`
- As well as deleted all the custom files in your core.

Normally after that your problem will be solved. I also invite you to avoid integrating external plugins into your core as you have just done. If after that your problem is solved please close the issue otherwise send a message.

**Comment by EmporiumNetwork** [comment]
so how do I use the plugin if its not a library?

**Comment by morcheysha77** [comment]
Once the plugin is in `/plugins`, you just have to follow this wiki: https://github.com/CustomiesDevs/Customies/wiki/Custom-Items
