### ISSUE TITLE
BlockIdentifier Not Passed by CustomiesBlockFactory Class

### ISSUE THREAD

**Issue by markeev** [CustomiesDevs/Customies#84]
**Description:**
The CustomiesBlockFactory class seems to not be passing the BlockIdentifier. This identifier is required for the creation of a Block class object.

**Expected behavior:**
I expected the CustomiesBlockFactory to pass the BlockIdentifier necessary for creating a Block object.

**Actual behavior:**
The BlockIdentifier is not being passed by the CustomiesBlockFactory class.

How can we use this now? The information on this topic in the wiki is outdated.

**Comment by unickorn** [comment]
What version of Customies are you using, PM4 or PM5?

**Comment by markeev** [comment]
pm 5, last

**Comment by TwistedAsylumMC** [comment]
You provide a callable that returns a Block, Customies does not need to do anything related to BlockIdentifier. You are correct in saying the wiki is outdated, I will fix it eventually but instead of using the ID that was previously provided, you need to create a type id which you can see an example of [here](https://github.com/pmmp/RegisterBlocksDemoPM5/blob/master/src/ExtraVanillaBlocks.php)

**Comment by markeev** [comment]
In the example you provided, it's unclear how to add textures to the block and set other important parameters. Should we expect an official wiki in the near future?

**Comment by TwistedAsylumMC** [comment]
This is an official wiki? Customies is not designed to be used by people with no knowledge of reading or PocketMine
